name: taqreeb
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  flutter_chat_ui: ^1.6.15
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_colorpicker: ^1.0.3
  table_calendar: ^3.0.0
  http: ^1.1.0
  flutter_secure_storage: ^7.0.0
  image_picker: ^0.8.7
  flutter_image_compress: ^1.1.0
  firebase_core: ^3.9.0
  dotenv: ^4.2.0
  flutter_dotenv: ^5.0.2
  cloud_firestore: ^5.6.0
  firebase_auth: ^5.3.4
  permission_handler: ^11.3.1
  flutter_contacts: ^1.1.9+2
  google_maps_flutter: ^2.10.0
  flutter_google_places_sdk: ^0.3.2+1
  url_launcher: ^6.3.1
  place_picker_google: ^0.0.14
  geolocator: ^13.0.2
  flutter_typeahead: ^5.2.0
  crop_your_image: ^2.0.0
  path_provider: ^2.1.5
  firebase_storage: ^12.3.7
  intl: ^0.18.0
  google_sign_in: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.2
  flutter_lints: ^5.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "/assets/images/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Mosk
      fonts:
        - asset: assets/fonts/Mosk Bold 700.ttf
          weight: 700
        - asset: assets/fonts/Mosk Extra-Bold 800.ttf
          weight: 800
        - asset: assets/fonts/Mosk Extra-Light 200.ttf
          weight: 200
        - asset: assets/fonts/Mosk Light 300.ttf
          weight: 300
