name: taqreeb
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  fonts:
  - family: Mosk
    fonts:
      - asset: assets\fonts\Mosk Bold 700.ttf
        weight: 700
      - asset: assets\fonts\Mosk Extra-Bold 800.ttf
        weight: 800
      - asset: assets\fonts\Mosk Extra-Light 200.ttf
        weight: 200
      - asset: assets\fonts\Mosk Light 300.ttf
        weight: 300
        
