# Generated by Django 4.2.20 on 2025-04-27 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=10000, null=True)),
                ('contactNumber', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('username', models.CharField(max_length=50, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=6, null=True)),
                ('profilePicture', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='flutter_user_set', related_query_name='flutter_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='flutter_user_set', related_query_name='flutter_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('additional_info', models.JSONField(default=dict)),
                ('has_reviewed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnic', models.TextField(null=True)),
                ('CNICFront', models.CharField(max_length=100, null=True)),
                ('CNICBack', models.CharField(max_length=100, null=True)),
                ('businessName', models.CharField(max_length=100)),
                ('profilepic', models.CharField(max_length=200, null=True)),
                ('Description', models.CharField(max_length=1100)),
                ('status', models.TextField(null=True)),
                ('balance', models.IntegerField(default=0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
                ('type', models.CharField(default='business', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1100)),
                ('themeColor', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('guestsmin', models.IntegerField(null=True)),
                ('guestsmax', models.IntegerField(null=True)),
                ('userID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('businessName', models.CharField(max_length=100, null=True)),
                ('portfolioLink', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=50, null=True)),
                ('profilepic', models.CharField(max_length=100, null=True)),
                ('Description', models.CharField(max_length=1100)),
                ('status', models.TextField(null=True)),
                ('balance', models.IntegerField(default=0)),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HomePageImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('priceMin', models.IntegerField()),
                ('priceMax', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1100)),
                ('rating', models.DecimalField(decimal_places=1, default=0, max_digits=2)),
                ('ratingCount', models.IntegerField(default=0)),
                ('basicPrice', models.IntegerField()),
                ('type', models.TextField(null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('booked_dates', models.JSONField(default=list)),
                ('freelancerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.freelancer')),
                ('ownerID', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.businessowner')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('status', models.CharField(default='processing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_info', models.JSONField(default=dict)),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Basic', max_length=100)),
                ('description', models.CharField(max_length=1100)),
                ('price', models.IntegerField()),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='TempInvitationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/tempCards/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolioLink', models.TextField()),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('venueType', models.CharField(choices=[('Banquet', 'Banquet'), ('Hall', 'Hall'), ('Lawn', 'Lawn'), ('Outdoor', 'Outdoor')], default='Banquet', max_length=50)),
                ('catering', models.CharField(choices=[('Internal', 'Internal'), ('External', 'External'), ('Internal & External', 'Internal & External')], default='Internal', max_length=50)),
                ('staff', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=10)),
                ('guestminAllowed', models.IntegerField(default=0)),
                ('guestmaxAllowed', models.IntegerField(default=0)),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='UserActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('search', 'Search Query'), ('category_click', 'Clicked Category'), ('service_click', 'Clicked Service'), ('filter', 'Applied Filter'), ('event_create', 'Created Event'), ('event_edit', 'Edited Event'), ('event_view', 'Viewed Event'), ('invite_card_view', 'Viewed Invitation Card'), ('service_view_duration', 'Time Spent on Service Page'), ('category_view_duration', 'Time Spent on Category Page'), ('book_venue', 'Booked Venue'), ('homepage_view_duration', 'Time Spent on Home Page'), ('ai_package_button_click', 'AI Package Button Clicked'), ('user_register', 'User Registered')], max_length=50)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.booking')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.order')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.packages')),
                ('receiverb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.businessowner')),
                ('receiverf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.freelancer')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s5', models.IntegerField(default=0)),
                ('s4', models.IntegerField(default=0)),
                ('s3', models.IntegerField(default=0)),
                ('s2', models.IntegerField(default=0)),
                ('s1', models.IntegerField(default=0)),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('review', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReactUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=10000)),
                ('profilePicturePath', models.CharField(blank=True, max_length=255, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='react_user_set', related_query_name='react_user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='react_user_set', related_query_name='react_user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='PicturesProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picturePath', models.CharField(max_length=100)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='PicturesPackages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picturePath', models.CharField(max_length=100)),
                ('packageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.packages')),
            ],
        ),
        migrations.CreateModel(
            name='PicturesListings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picturePath', models.CharField(max_length=100)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='PhotographyPlaces',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('Studio', 'Studio'), ('Outdoor', 'Outdoor'), ('Indoor', 'Indoor'), ('Destination', 'Destination'), ('Event', 'Event')], default='Studio', max_length=100)),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Photographers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolioLink', models.CharField(max_length=100)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('payment_method', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_details', models.JSONField(default=dict)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Parlors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('members', models.IntegerField(null=True)),
                ('phone', models.CharField(max_length=100, null=True)),
                ('functionId', models.IntegerField(null=True)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicDesigners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolioLink', models.CharField(max_length=100)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('eventtypeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.eventtype')),
            ],
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('guestsmin', models.IntegerField(null=True)),
                ('guestsmax', models.IntegerField(null=True)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
            ],
        ),
        migrations.CreateModel(
            name='FCMTokens',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('token', models.TextField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Decorators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decorType', models.CharField(choices=[('Floral', 'Floral'), ('Lighting', 'Lighting'), ('Drapery', 'Drapery'), ('Furniture', 'Furniture'), ('Themed', 'Themed')], default='Floral', max_length=50)),
                ('catering', models.CharField(choices=[('Provided', 'Provided'), ('Not Provided', 'Not Provided')], default='Not Provided', max_length=50)),
                ('staff', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Mixed', 'Mixed')], default='Mixed', max_length=50)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1100)),
                ('isChecked', models.BooleanField()),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
                ('functionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.functions')),
            ],
        ),
        migrations.CreateModel(
            name='Caterers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceType', models.CharField(choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Other', 'Other')], default='Wedding', max_length=100)),
                ('cateringOptions', models.CharField(choices=[('Buffet', 'Buffet'), ('Plated', 'Plated'), ('Family Style', 'Family Style'), ('Food Stations', 'Food Stations'), ('Cocktail Reception', 'Cocktail Reception')], default='Buffet', max_length=100)),
                ('staff', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Mixed', 'Mixed')], default='Mixed', max_length=100)),
                ('expertise', models.CharField(choices=[('Pakistani', 'Pakistani'), ('Chinese', 'Chinese'), ('Continental', 'Continental'), ('Italian', 'Italian'), ('Desserts', 'Desserts')], default='Pakistani', max_length=100)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='CarRenters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceType', models.CharField(choices=[('Luxury', 'Luxury'), ('Economy', 'Economy'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Van', 'Van')], default='Economy', max_length=100)),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('info', models.TextField()),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.order')),
                ('ownerb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.businessowner')),
                ('ownerf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='BookingCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.DateTimeField(null=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('status', models.CharField(max_length=100)),
                ('functionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.functions')),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.listing'),
        ),
        migrations.AddField(
            model_name='booking',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.packages'),
        ),
        migrations.AddField(
            model_name='booking',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.product'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BookedSlots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.DateField()),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bankName', models.TextField()),
                ('accountNumber', models.TextField()),
                ('IBANNumber', models.TextField()),
                ('accountHolderName', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('isPer', models.BooleanField()),
                ('perType', models.CharField(max_length=50)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('listing', 'Listing'), ('product', 'Product'), ('package', 'Package')], max_length=10)),
                ('item_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.cart')),
            ],
            options={
                'unique_together': {('cart', 'item_type', 'item_id')},
            },
        ),
    ]
