# Generated by Django 4.2.20 on 2025-04-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilePicture',
        ),
        migrations.AddField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('search', 'Search Query'), ('category_click', 'Clicked Category'), ('service_click', 'Clicked Service'), ('filter', 'Applied Filter')], max_length=50),
        ),
    ]
