# Generated by Django 5.0.8 on 2024-12-21 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_functiontype_eventtypeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessowner',
            name='status',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='guestmaxAllowed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venue',
            name='guestminAllowed',
            field=models.IntegerField(default=0),
        ),
    ]
