# Generated by Django 5.0.8 on 2025-05-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_listing_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='staff',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Both', 'Both')], default='Male', max_length=10),
        ),
    ]
