# Generated by Django 5.0.8 on 2024-12-21 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_businessowner_status_venue_guestmaxallowed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packages',
            name='name',
            field=models.CharField(default='Basic', max_length=100),
        ),
    ]
