# Generated by Django 5.0.8 on 2025-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_venue_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrenters',
            old_name='listingID',
            new_name='listingId',
        ),
        migrations.RenameField(
            model_name='photographyplaces',
            old_name='listingID',
            new_name='listingId',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='listingID',
            new_name='listingId',
        ),
        migrations.RenameField(
            model_name='reviewdetails',
            old_name='listingID',
            new_name='listingId',
        ),
        migrations.RenameField(
            model_name='venue',
            old_name='listingID',
            new_name='listingId',
        ),
        migrations.AlterField(
            model_name='bookingcart',
            name='type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='CNICBack',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='CNICFront',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='cnic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='profilepic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='decorators',
            name='catering',
            field=models.CharField(choices=[('Provided', 'Provided'), ('Not provided', 'Not provided')], default='Not Provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='businessName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='cnic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profilepic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.TextField(blank=True),
        ),
    ]
