# Generated by Django 5.0.8 on 2025-05-09 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_venue_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='bookingcart',
            name='type',
            field=models.CharField(blank=True, default='Venue', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='CNICBack',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='CNICFront',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='cnic',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='profilepic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='decorators',
            name='catering',
            field=models.CharField(choices=[('Provided', 'Provided'), ('Not provided', 'Not provided')], default='Not Provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='businessName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='cnic',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='profilepic',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='freelancer',
            name='status',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='phone',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='type',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='FunctionService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('function', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.functions')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
                ('package', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.packages')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionServiceAddOn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.addons')),
                ('function_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.functionservice')),
            ],
        ),
        migrations.CreateModel(
            name='FunctionServiceProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('function_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.functionservice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
    ]
