# Generated by Django 5.0.8 on 2025-05-19 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_listingid_carrenters_listingid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='listingID',
            new_name='listingId',
        ),
        migrations.RenameField(
            model_name='reviewdetails',
            old_name='listingID',
            new_name='listingId',
        ),
    ]
