# Generated by Django 5.0.8 on 2025-05-28 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_notificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addons',
            name='perType',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='functionId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.functions'),
        ),
    ]
