# Generated by Django 5.0.8 on 2025-05-28 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_addons_pertype_alter_guestlist_functionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='themeColor',
        ),
    ]
