# Generated by Django 5.0.8 on 2025-06-01 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_events_themecolor'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='videoLink',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
