# Generated by Django 5.0.8 on 2025-06-01 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_listing_videolink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='functionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.functions'),
        ),
    ]
