# Generated by Django 5.0.8 on 2024-12-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_carrenters_servicetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrenters',
            name='drivers',
        ),
        migrations.RemoveField(
            model_name='packages',
            name='type',
        ),
        migrations.RemoveField(
            model_name='parlors',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='salons',
            name='slot',
        ),
        migrations.AddField(
            model_name='businessowner',
            name='profilepic',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
