# Generated by Django 5.0.8 on 2024-12-31 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_user_age_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessowner',
            name='businessUsername',
        ),
        migrations.RemoveField(
            model_name='freelancer',
            name='businessUsername',
        ),
    ]
