# Generated by Django 5.0.8 on 2024-12-31 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_remove_businessowner_businessusername_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='businessName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
