# Generated by Django 5.0.8 on 2024-12-31 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_freelancer_businessname'),
    ]

    operations = [
        migrations.AddField(
            model_name='freelancer',
            name='cnic',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='profilePic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='status',
            field=models.TextField(null=True),
        ),
    ]
