# Generated by Django 5.0.8 on 2025-03-23 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_merge_20250323_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivity',
            name='duration_seconds',
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('search', 'Search Query'), ('category_click', 'Clicked Category'), ('service_click', 'Clicked Service'), ('filter', 'Applied Filter'), ('event_create', 'Created Event'), ('event_edit', 'Edited Event'), ('event_view', 'Viewed Event'), ('invite_card_view', 'Viewed Invitation Card'), ('service_view_duration', 'Time Spent on Service Page'), ('category_view_duration', 'Time Spent on Category Page'), ('book_venue', 'Booked Venue')], max_length=50),
        ),
        migrations.DeleteModel(
            name='UserEvent',
        ),
    ]
