# Generated by Django 5.0.8 on 2025-04-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_review_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='userID',
            field=models.IntegerField(null=True),
        ),
    ]
