# Generated by Django 5.0.8 on 2025-04-05 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_events_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='userID',
        ),
    ]
