# Generated by Django 5.0.8 on 2025-04-05 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_remove_events_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='uid',
            new_name='userID',
        ),
    ]
