# Generated by Django 4.2.20 on 2025-04-24 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_tempinvitationcard_businessowner_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='listing',
        ),
        migrations.AddField(
            model_name='transaction',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.packages'),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('search', 'Search Query'), ('category_click', 'Clicked Category'), ('service_click', 'Clicked Service'), ('filter', 'Applied Filter'), ('event_create', 'Created Event'), ('event_edit', 'Edited Event'), ('event_view', 'Viewed Event'), ('invite_card_view', 'Viewed Invitation Card'), ('service_view_duration', 'Time Spent on Service Page'), ('category_view_duration', 'Time Spent on Category Page'), ('book_venue', 'Booked Venue'), ('homepage_view_duration', 'Time Spent on Home Page'), ('ai_package_button_click', 'AI Package Button Clicked')], max_length=50),
        ),
    ]
