# Generated by Django 4.2.20 on 2025-04-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_remove_transaction_listing_transaction_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='warned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='warning_reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('search', 'Search Query'), ('category_click', 'Clicked Category'), ('service_click', 'Clicked Service'), ('filter', 'Applied Filter'), ('event_create', 'Created Event'), ('event_edit', 'Edited Event'), ('event_view', 'Viewed Event'), ('invite_card_view', 'Viewed Invitation Card'), ('service_view_duration', 'Time Spent on Service Page'), ('category_view_duration', 'Time Spent on Category Page'), ('book_venue', 'Booked Venue'), ('homepage_view_duration', 'Time Spent on Home Page'), ('ai_package_button_click', 'AI Package Button Clicked'), ('user_register', 'User Registered')], max_length=50),
        ),
    ]
