# Generated by Django 4.2.20 on 2025-04-24 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_user_is_banned_user_warned_at_user_warning_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReactUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='react_profile_pics/')),
            ],
        ),
    ]
