# Generated by Django 4.2.20 on 2025-04-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_reactuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reactuser',
            old_name='user_id',
            new_name='id',
        ),
    ]
