# Generated by Django 5.0.8 on 2024-12-17 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIEventQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=100)),
                ('questionType', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BakersAndSweets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessOwner',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnic', models.TextField(null=True)),
                ('category', models.TextField(null=True)),
                ('CNICFront', models.CharField(max_length=100)),
                ('CNICBack', models.CharField(max_length=100)),
                ('businessName', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('businessUsername', models.CharField(max_length=50)),
                ('Description', models.CharField(max_length=1100)),
            ],
        ),
        migrations.CreateModel(
            name='CarRenters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceType', models.CharField(max_length=100)),
                ('drivers', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userID', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1100)),
                ('themeColor', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('guestsmin', models.IntegerField(null=True)),
                ('guestsmax', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FunctionType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('contactNumber', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=6)),
                ('profilePicture', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pricePerDay', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('seats', models.IntegerField()),
                ('driver', models.IntegerField()),
                ('picture', models.CharField(max_length=255)),
                ('carRenterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.carrenters')),
            ],
        ),
        migrations.CreateModel(
            name='DesertItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('picture', models.CharField(max_length=255)),
                ('bakersId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bakersandsweets')),
            ],
        ),
        migrations.CreateModel(
            name='Functions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('budget', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('date', models.DateField(null=True)),
                ('guestsmin', models.IntegerField(null=True)),
                ('guestsmax', models.IntegerField(null=True)),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
            ],
        ),
        migrations.CreateModel(
            name='CheckList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=1100)),
                ('isChecked', models.BooleanField()),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
                ('functionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.functions')),
            ],
        ),
        migrations.CreateModel(
            name='GuestList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('members', models.IntegerField()),
                ('phone', models.CharField(max_length=100)),
                ('functionId', models.IntegerField()),
                ('eventId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('priceMin', models.IntegerField()),
                ('priceMax', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1100)),
                ('basicPrice', models.IntegerField()),
                ('type', models.TextField(null=True)),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.businessowner')),
            ],
        ),
        migrations.CreateModel(
            name='GraphicDesigners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolioLink', models.CharField(max_length=100)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Decorators',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('decorType', models.CharField(max_length=50)),
                ('catering', models.CharField(max_length=50)),
                ('staff', models.CharField(max_length=50)),
                ('slot', models.DateTimeField()),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Caterers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('serviceType', models.TextField()),
                ('cateringOptions', models.CharField(max_length=50)),
                ('staff', models.CharField(max_length=50)),
                ('expertise', models.CharField(max_length=100)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.AddField(
            model_name='carrenters',
            name='listingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing'),
        ),
        migrations.AddField(
            model_name='bakersandsweets',
            name='listingID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing'),
        ),
        migrations.CreateModel(
            name='AddOns',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('isPer', models.BooleanField()),
                ('perType', models.CharField(max_length=50)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('pricePerKg', models.IntegerField()),
                ('picture', models.CharField(max_length=100)),
                ('cateringId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.caterers')),
            ],
        ),
        migrations.CreateModel(
            name='Packages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('description', models.CharField(max_length=1100)),
                ('price', models.IntegerField()),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Parlors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.DateTimeField()),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Photographers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolioLink', models.CharField(max_length=100)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='PicturesListings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picturePath', models.CharField(max_length=100)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionOptions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('optionType', models.TextField()),
                ('name', models.TextField()),
                ('questionId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.aieventquestions')),
            ],
        ),
        migrations.CreateModel(
            name='Salons',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.CharField(max_length=100)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.DecimalField(decimal_places=10, max_digits=20)),
                ('review', models.CharField(max_length=100)),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('price', models.IntegerField()),
                ('slot', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('ServiceID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
                ('ownerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.businessowner')),
                ('packageID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.packages')),
                ('customerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Freelancer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('businessUsername', models.CharField(max_length=100)),
                ('portfolioLink', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1100)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('ownerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.businessowner')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.menuitems')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
        migrations.AddField(
            model_name='businessowner',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('venueType', models.CharField(max_length=100)),
                ('catering', models.CharField(max_length=100)),
                ('staff', models.CharField(max_length=100)),
                ('slot', models.DateTimeField()),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='VideoEditors',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('portfolioLink', models.TextField()),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
    ]
