# Generated by Django 5.0.8 on 2024-11-30 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='functions',
            name='Date',
            field=models.DateField(null=True),
        ),
    ]
