# Generated by Django 5.0.8 on 2024-12-06 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_listingid_bakersandsweets_listingid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freelancer',
            name='businessName',
        ),
        migrations.AddField(
            model_name='events',
            name='guestsmax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='guestsmin',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='functions',
            name='guestsmax',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='functions',
            name='guestsmin',
            field=models.IntegerField(null=True),
        ),
    ]
