# Generated by Django 5.0.8 on 2024-12-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_remove_freelancer_businessname_events_guestsmax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contactNumber',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
