# Generated by Django 5.0.8 on 2024-12-21 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_packages_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookedSlots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.DateField()),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
                ('venueId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.venue')),
            ],
        ),
    ]
