# Generated by Django 5.0.8 on 2024-12-13 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_listing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicturesListings',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.CharField(max_length=100)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
    ]
