# Generated by Django 5.0.8 on 2024-12-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_pictureslistings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pictureslistings',
            old_name='picture',
            new_name='picturePath',
        ),
    ]
