# Generated by Django 5.0.8 on 2024-12-13 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_picture_pictureslistings_picturepath'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pictureslistings',
            name='picturePath',
            field=models.TextField(),
        ),
    ]
