# Generated by Django 5.0.8 on 2024-12-22 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_checklist_eventid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='eventId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.events'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='functionId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.functions'),
        ),
    ]
