# Generated by Django 5.0.8 on 2024-12-23 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_checklist_eventid_alter_checklist_functionid'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageImages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BookingCart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('slot', models.DateTimeField()),
                ('status', models.CharField(max_length=100)),
                ('eventId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.events')),
                ('functionId', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.functions')),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
