# Generated by Django 5.0.8 on 2024-12-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_remove_bookingcart_eventid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookedslots',
            name='venueId',
        ),
        migrations.AlterField(
            model_name='bookingcart',
            name='slot',
            field=models.DateTimeField(null=True),
        ),
    ]
