# Generated by Django 5.0.8 on 2024-12-24 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_remove_businessowner_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrenters',
            name='serviceType',
            field=models.CharField(choices=[('Luxury', 'Luxury'), ('Economy', 'Economy'), ('SUV', 'SUV'), ('Convertible', 'Convertible'), ('Van', 'Van')], default='Economy', max_length=100),
        ),
        migrations.AlterField(
            model_name='caterers',
            name='cateringOptions',
            field=models.CharField(choices=[('Buffet', 'Buffet'), ('Plated', 'Plated'), ('Family Style', 'Family Style'), ('Food Stations', 'Food Stations'), ('Cocktail Reception', 'Cocktail Reception')], default='Buffet', max_length=100),
        ),
        migrations.AlterField(
            model_name='caterers',
            name='expertise',
            field=models.CharField(choices=[('Pakistani', 'Pakistani'), ('Chinese', 'Chinese'), ('Continental', 'Continental'), ('Italian', 'Italian'), ('Desserts', 'Desserts')], default='Pakistani', max_length=100),
        ),
        migrations.AlterField(
            model_name='caterers',
            name='serviceType',
            field=models.CharField(choices=[('Wedding', 'Wedding'), ('Corporate', 'Corporate'), ('Birthday', 'Birthday'), ('Anniversary', 'Anniversary'), ('Other', 'Other')], default='Wedding', max_length=100),
        ),
        migrations.AlterField(
            model_name='caterers',
            name='staff',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Mixed', 'Mixed')], default='Mixed', max_length=100),
        ),
        migrations.AlterField(
            model_name='decorators',
            name='catering',
            field=models.CharField(choices=[('Provided', 'Provided'), ('Not Provided', 'Not Provided')], default='Not Provided', max_length=50),
        ),
        migrations.AlterField(
            model_name='decorators',
            name='decorType',
            field=models.CharField(choices=[('Floral', 'Floral'), ('Lighting', 'Lighting'), ('Drapery', 'Drapery'), ('Furniture', 'Furniture'), ('Themed', 'Themed')], default='Floral', max_length=50),
        ),
        migrations.AlterField(
            model_name='decorators',
            name='staff',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Mixed', 'Mixed')], default='Mixed', max_length=50),
        ),
        migrations.AlterField(
            model_name='photographyplaces',
            name='type',
            field=models.CharField(choices=[('Studio', 'Studio'), ('Outdoor', 'Outdoor'), ('Indoor', 'Indoor'), ('Destination', 'Destination'), ('Event', 'Event')], default='Studio', max_length=100),
        ),
    ]
