# Generated by Django 4.2.20 on 2025-04-27 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_banned',
        ),
        migrations.RemoveField(
            model_name='user',
            name='warned_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='warning_reason',
        ),
    ]
