# Generated by Django 5.0.8 on 2024-12-21 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_photographyplaces'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='cateringId',
        ),
        migrations.AddField(
            model_name='menuitems',
            name='listingId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.listing'),
        ),
    ]
