# Generated by Django 5.0.8 on 2024-12-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_menuitems_cateringid_menuitems_listingid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestlist',
            name='functionId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='members',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='guestlist',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
