# Generated by Django 5.0.8 on 2024-12-22 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_guestlist_functionid_alter_guestlist_members_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist',
            name='eventId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.events'),
        ),
    ]
