# Generated by Django 5.0.8 on 2024-12-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_homepageimages_bookingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingcart',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
