# Generated by Django 5.0.8 on 2024-12-23 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_bookingcart_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingcart',
            name='eventId',
        ),
    ]
