# Generated by Django 5.0.8 on 2024-12-27 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_carrenters_drivers_remove_packages_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessowner',
            name='CNICBack',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='CNICFront',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
