# Generated by Django 5.0.8 on 2024-12-28 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_user_groups_user_is_superuser_user_last_login_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decorators',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='slot',
        ),
    ]
