# Generated by Django 5.0.8 on 2025-01-01 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_freelancer_cnic_freelancer_profilepic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='freelancerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.freelancer'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='ownerID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.businessowner'),
        ),
    ]
