# Generated by Django 5.0.8 on 2025-01-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_listing_freelancerid_alter_listing_ownerid'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='type',
            field=models.CharField(default='business', max_length=100),
        ),
    ]
