# Generated by Django 5.0.8 on 2025-01-20 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_categories_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='freelancer',
            old_name='profilePic',
            new_name='profilepic',
        ),
    ]
