# Generated by Django 5.0.8 on 2025-01-20 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_rename_description_freelancer_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freelancer',
            old_name='userId',
            new_name='userID',
        ),
    ]
