# Generated by Django 5.1.4 on 2025-03-14 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_useractivity_userevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivity',
            name='action',
            field=models.CharField(choices=[('search', 'Search Query'), ('category_click', 'Clicked Category'), ('service_click', 'Clicked Service'), ('filter', 'Applied Filter'), ('event_create', 'Created Event'), ('event_edit', 'Edited Event'), ('event_view', 'Viewed Event'), ('invite_card_view', 'Viewed Invitation Card'), ('service_view_duration', 'Time Spent on Service Page')], max_length=50),
        ),
    ]
