# Generated by Django 5.0.8 on 2025-03-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_useractivity_duration_seconds_and_more'),
        ('myapp', '0033_transaction'),
    ]

    operations = [
    ]
