# Generated by Django 5.0.8 on 2025-03-28 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_remove_useractivity_duration_seconds_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
