# Generated by Django 5.0.8 on 2025-04-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_delete_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='ratingCount',
            field=models.IntegerField(default=0),
        ),
    ]
