# Generated by Django 5.0.8 on 2025-04-03 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_review_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('s5', models.IntegerField(default=0)),
                ('s4', models.IntegerField(default=0)),
                ('s3', models.IntegerField(default=0)),
                ('s2', models.IntegerField(default=0)),
                ('s1', models.IntegerField(default=0)),
                ('listingID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
    ]
