# Generated by Django 5.0.8 on 2025-04-04 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_reviewdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desertitems',
            name='bakersId',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='receiver',
            new_name='receiverb',
        ),
        migrations.AddField(
            model_name='transaction',
            name='receiverf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.freelancer'),
        ),
        migrations.DeleteModel(
            name='BakersAndSweets',
        ),
        migrations.DeleteModel(
            name='DesertItems',
        ),
    ]
