# Generated by Django 5.0.8 on 2025-04-11 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_rename_uid_events_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempInvitationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='uploads/tempCards/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='businessowner',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='freelancer',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bankName', models.TextField()),
                ('accountNumber', models.TextField()),
                ('IBANNumber', models.TextField()),
                ('accountHolderName', models.TextField()),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.IntegerField()),
                ('info', models.TextField()),
                ('ownerb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.businessowner')),
                ('ownerf', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.freelancer')),
            ],
        ),
        migrations.CreateModel(
            name='PicturesPackages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picturePath', models.CharField(max_length=100)),
                ('packageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.packages')),
            ],
        ),
    ]
