# Generated by Django 5.0.8 on 2025-04-23 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_tempinvitationcard_businessowner_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='listing',
        ),
        migrations.AddField(
            model_name='transaction',
            name='package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.packages'),
        ),
    ]
