# Generated by Django 5.0.8 on 2025-04-26 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_remove_transaction_listing_transaction_package'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionoptions',
            name='questionId',
        ),
        migrations.RemoveField(
            model_name='businesstransaction',
            name='ownerb',
        ),
        migrations.RemoveField(
            model_name='businesstransaction',
            name='ownerf',
        ),
        migrations.RemoveField(
            model_name='cars',
            name='carRenterId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='ownerId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='productId',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='userId',
        ),
        migrations.RemoveField(
            model_name='menuitems',
            name='listingId',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='package',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiverb',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receiverf',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender',
        ),
        migrations.AddField(
            model_name='listing',
            name='booked_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='listing',
            name='status',
            field=models.CharField(default='active', max_length=20),
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('listingId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.listing')),
            ],
        ),
        migrations.CreateModel(
            name='PicturesProducts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('picturePath', models.CharField(max_length=100)),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
            ],
        ),
        migrations.DeleteModel(
            name='AIEventQuestions',
        ),
        migrations.DeleteModel(
            name='QuestionOptions',
        ),
        migrations.DeleteModel(
            name='BusinessTransaction',
        ),
        migrations.DeleteModel(
            name='Cars',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='MenuItems',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
